apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: vladimir44/microservices-demo-frontend:0.1
    name: frontend
    resources: {}
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "PRODUCT_CATALOG_SERVICE"
      - name: CURRENCY_SERVICE_ADDR
        value: "CURRENCY_SERVICE"
      - name: CART_SERVICE_ADDR
        value: "fake"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "fake"
      - name: CHECKOUT_SERVICE_ADDR
        value: "fake"
      - name: SHIPPING_SERVICE_ADDR
        value: "fake"
      - name: AD_SERVICE_ADDR
        value: "fake"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}