apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
      matchLabels:
        app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: vladimir44/microservices-demo-payment-service:0.0.2
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"