apiVersion: v1                       # Версия API
kind: Pod                            # Объект, который создаем
metadata:
  name: web                          # Название Pod
  labels:                            # Метки в формате key: value
    app: web
spec:                                # Описание Pod
  initContainers:
    - name: web-init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app
  containers:                        # Описание контейнеров внутри Pod
    - name: web                      # Название контейнера
      image: vladimir44/k8s-app:0.4  # Образ из которого создается контейнер
      readinessProbe:                # Добавим проверку готовности
        httpGet:
          path: /index.html # контент
          port: 80
      livenessProbe:
        tcpSocket:
          port: 8000
      volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
